services:
  postgres:
    container_name: squirrel-test
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: squirrel_test
      POSTGRES_DB: squirrel_test
    ports:
      - 5432:5432
    hostname: postgres
    expose:
      - 5432
